# Generated by Django 5.0.1 on 2024-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.PositiveIntegerField()),
                ('user_resume', models.FileField(upload_to='')),
                ('prediction', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
