# Generated by Django 5.0.1 on 2024-02-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_prediction_resume_data_cv_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_data',
            name='user_email',
            field=models.CharField(max_length=50),
        ),
    ]
