# Generated by Django 5.0.1 on 2024-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resume_data_mock_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_data',
            name='actual_skills',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume_data',
            name='no_of_pages',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume_data',
            name='recommended_skills',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume_data',
            name='resume_score',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume_data',
            name='user_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
